"""add_session_token_encrypted_to_aws_accounts

Revision ID: b600551cf092
Revises: 31380ca807ca
Create Date: 2026-08-08 13:21:58.511940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b600551cf092'
down_revision = '31380ca807ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aws_accounts', schema=None) as batch_op:
        batch_op.drop_column('session_token_encrypted')

    # ### end Alembic commands ###
